#2 Sprint 10
idleCat90/java-filmorate pull request #5
Opened 2023-09-07 18:39 UTC by idleCat90

2023-09-08 18:16 UTC, Yang-Pi requested changes

2023-09-08 18:16 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getAllFilms().stream()
Логика проверки наличия сущности в хранилище оптимальнее реализовывать в рамках хранилища (это мб SQL запрос или просто проверка в мапе), потому что запрос всех фильмов мб оочень дорогой операцией

2023-09-08 18:16 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.getUserById(id);
Обрати внимание на эту операцию - ты запрашиваешь пользователя, но при проверки его наличия ты тоже его же запрашивал (+ еще всех остальных). Если пользователя нет в хранилище, то userStorage.getUserById(id) просто вернет null, поэтому логику валидации ты как раз можешь на этом построить

2023-09-08 18:16 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.getUserById(id);
Актуально и для остальных методов

2023-09-08 18:16 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/validator/LoginConstraintValidator.java
> +        if (login == null || login.isEmpty() || login.isBlank()) {
isBlank включает в себя проверку isEmpty()

2023-09-08 18:16 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @LoginConstraint
А почему не хочешь использовать уже известные аннотации - isBlank и nonNull ?

2023-09-10 17:24 UTC, idleCat90 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @LoginConstraint
потому что нужно еще исключить строки, содержащие пробелы

2023-09-11 08:21 UTC, idleCat90 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @LoginConstraint
упаковал всю логику ограничений в одну аннотацию для каждого из таких полей (releaseDate, login)

2023-09-11 12:39 UTC, Yang-Pi approved these changes

2023-09-11 17:36 UTC, merged