#3 Sprint 11
idleCat90/java-filmorate pull request #6
Opened 2023-10-09 19:14 UTC by idleCat90

2023-10-10 16:38 UTC, Yang-Pi requested changes
Общий комментарий: не хвататет логирования исключительных ситуаций, при дебаге это очень полезная информация.

2023-10-10 16:38 UTC, Yang-Pi commented on pom.xml
Унифицируй этот файл в соответсвии с code style doc: отступ - 4 пробела; сейчас где-то 8, где-то 4

2023-10-10 16:38 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/impl/FilmDbStorage.java
> +package ru.yandex.practicum.filmorate.impl;
Этот пакет не совсем подходящий для этого (и подобных) класса, потому что impl чего? проще переместить содержимое этого пакета в подпакет dao

2023-10-10 16:38 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/impl/FilmDbStorage.java
> +        film.setMpa(makeMpa(mpaId));
Метод updateFilm выполняется, как PUT запрос, те полноценное обновление объекта, это значит, что не должно быть доп запросов, которые обогащают (data enrichment) объект, полученный методом.

2023-10-10 16:39 UTC, Yang-Pi commented
Не увидел схему бд картинкой, по ТЗ ее тоже нужно добавить в PR

2023-10-11 13:20 UTC, idleCat90 commented on src/main/java/ru/yandex/practicum/filmorate/impl/FilmDbStorage.java
> +        film.setMpa(makeMpa(mpaId));
Вот тут не вполне понял, о чем речь. В базу попадает объект, переданный в качестве аргумента. А метод возвращает экземпляр класса, актуализированный согласно новому состоянию базы. 
Что я делаю не так?

Прости, если вопрос окажется тупым) - за месяц без фидбэка глаз замылился.И вообще, решением этого спринта я не вполне доволен, ощущение, что костыли торчат,  и можно более элегантно и эффективно сделать. На каникулах попробую еще раз для себя написать.

2023-10-11 15:10 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/impl/FilmDbStorage.java
> +        film.setMpa(makeMpa(mpaId));
> Прости, если вопрос окажется тупым) 
за такое извиняться не нужно, потому что 1) это не глупый вопрос 2) это ок задавать вопросы

2023-10-11 15:13 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/impl/FilmDbStorage.java
> +        film.setMpa(makeMpa(mpaId));
> В базу попадает объект, переданный в качестве аргумента.

да, но ты потом делаешь еще запросы для mpa и жанров, они как раз лишние

2023-10-11 18:55 UTC, idleCat90 commented on src/main/java/ru/yandex/practicum/filmorate/impl/FilmDbStorage.java
> +        film.setMpa(makeMpa(mpaId));
Без этих запросов тесты постмана у меня не проходятся.

2023-10-11 20:52 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/impl/FilmDbStorage.java
> +        film.setMpa(makeMpa(mpaId));
Хорошо, понял

2023-10-12 05:55 UTC, Yang-Pi approved these changes

2023-10-12 08:48 UTC, merged